<?php

namespace App\Services;

class CountryService
{
    private static array $countries = [
        ['value' => 'AF', 'en' => 'Afghanistan', 'fi' => 'Afganistan'],
        ['value' => 'AL', 'en' => 'Albania', 'fi' => 'Albania'],
        ['value' => 'DZ', 'en' => 'Algeria', 'fi' => 'Algeria'],
        ['value' => 'AD', 'en' => 'Andorra', 'fi' => 'Andorra'],
        ['value' => 'AO', 'en' => 'Angola', 'fi' => 'Angola'],
        ['value' => 'AG', 'en' => 'Antigua and Barbuda', 'fi' => 'Antigua ja Barbuda'],
        ['value' => 'AR', 'en' => 'Argentina', 'fi' => 'Argentiina'],
        ['value' => 'AM', 'en' => 'Armenia', 'fi' => 'Armenia'],
        ['value' => 'AU', 'en' => 'Australia', 'fi' => 'Australia'],
        ['value' => 'AT', 'en' => 'Austria', 'fi' => 'Itävalta'],
        ['value' => 'AZ', 'en' => 'Azerbaijan', 'fi' => 'Azerbaidžan'],
        ['value' => 'BS', 'en' => 'Bahamas', 'fi' => 'Bahama'],
        ['value' => 'BH', 'en' => 'Bahrain', 'fi' => 'Bahrain'],
        ['value' => 'BD', 'en' => 'Bangladesh', 'fi' => 'Bangladesh'],
        ['value' => 'BB', 'en' => 'Barbados', 'fi' => 'Barbados'],
        ['value' => 'BY', 'en' => 'Belarus', 'fi' => 'Valko-Venäjä'],
        ['value' => 'BE', 'en' => 'Belgium', 'fi' => 'Belgia'],
        ['value' => 'BZ', 'en' => 'Belize', 'fi' => 'Belize'],
        ['value' => 'BJ', 'en' => 'Benin', 'fi' => 'Benin'],
        ['value' => 'BT', 'en' => 'Bhutan', 'fi' => 'Bhutan'],
        ['value' => 'BO', 'en' => 'Bolivia', 'fi' => 'Bolivia'],
        ['value' => 'BA', 'en' => 'Bosnia and Herzegovina', 'fi' => 'Bosnia ja Hertsegovina'],
        ['value' => 'BW', 'en' => 'Botswana', 'fi' => 'Botswana'],
        ['value' => 'BR', 'en' => 'Brazil', 'fi' => 'Brasilia'],
        ['value' => 'BN', 'en' => 'Brunei', 'fi' => 'Brunei'],
        ['value' => 'BG', 'en' => 'Bulgaria', 'fi' => 'Bulgaria'],
        ['value' => 'BF', 'en' => 'Burkina Faso', 'fi' => 'Burkina Faso'],
        ['value' => 'BI', 'en' => 'Burundi', 'fi' => 'Burundi'],
        ['value' => 'CV', 'en' => 'Cabo Verde', 'fi' => 'Kap Verde'],
        ['value' => 'KH', 'en' => 'Cambodia', 'fi' => 'Kambodža'],
        ['value' => 'CM', 'en' => 'Cameroon', 'fi' => 'Kamerun'],
        ['value' => 'CA', 'en' => 'Canada', 'fi' => 'Kanada'],
        ['value' => 'CF', 'en' => 'Central African Republic', 'fi' => 'Keski-Afrikan tasavalta'],
        ['value' => 'TD', 'en' => 'Chad', 'fi' => 'Tšad'],
        ['value' => 'CL', 'en' => 'Chile', 'fi' => 'Chile'],
        ['value' => 'CN', 'en' => 'China', 'fi' => 'Kiina'],
        ['value' => 'CO', 'en' => 'Colombia', 'fi' => 'Kolumbia'],
        ['value' => 'KM', 'en' => 'Comoros', 'fi' => 'Komorit'],
        ['value' => 'CG', 'en' => 'Congo', 'fi' => 'Kongo'],
        ['value' => 'CD', 'en' => 'Congo, Democratic Republic of the', 'fi' => 'Kongon demokraattinen tasavalta'],
        ['value' => 'CR', 'en' => 'Costa Rica', 'fi' => 'Costa Rica'],
        ['value' => 'HR', 'en' => 'Croatia', 'fi' => 'Kroatia'],
        ['value' => 'CU', 'en' => 'Cuba', 'fi' => 'Kuuba'],
        ['value' => 'CY', 'en' => 'Cyprus', 'fi' => 'Kypros'],
        ['value' => 'CZ', 'en' => 'Czech Republic', 'fi' => 'Tšekki'],
        ['value' => 'DK', 'en' => 'Denmark', 'fi' => 'Tanska'],
        ['value' => 'DJ', 'en' => 'Djibouti', 'fi' => 'Djibouti'],
        ['value' => 'DM', 'en' => 'Dominica', 'fi' => 'Dominica'],
        ['value' => 'DO', 'en' => 'Dominican Republic', 'fi' => 'Dominikaaninen tasavalta'],
        ['value' => 'EC', 'en' => 'Ecuador', 'fi' => 'Ecuador'],
        ['value' => 'EG', 'en' => 'Egypt', 'fi' => 'Egypti'],
        ['value' => 'SV', 'en' => 'El Salvador', 'fi' => 'El Salvador'],
        ['value' => 'GQ', 'en' => 'Equatorial Guinea', 'fi' => 'Päiväntasaajan Guinea'],
        ['value' => 'ER', 'en' => 'Eritrea', 'fi' => 'Eritrea'],
        ['value' => 'EE', 'en' => 'Estonia', 'fi' => 'Viro'],
        ['value' => 'SZ', 'en' => 'Eswatini', 'fi' => 'Eswatini'],
        ['value' => 'ET', 'en' => 'Ethiopia', 'fi' => 'Etiopia'],
        ['value' => 'FJ', 'en' => 'Fiji', 'fi' => 'Fidži'],
        ['value' => 'FI', 'en' => 'Finland', 'fi' => 'Suomi'],
        ['value' => 'FR', 'en' => 'France', 'fi' => 'Ranska'],
        ['value' => 'GA', 'en' => 'Gabon', 'fi' => 'Gabon'],
        ['value' => 'GM', 'en' => 'Gambia', 'fi' => 'Gambia'],
        ['value' => 'GE', 'en' => 'Georgia', 'fi' => 'Georgia'],
        ['value' => 'DE', 'en' => 'Germany', 'fi' => 'Saksa'],
        ['value' => 'GH', 'en' => 'Ghana', 'fi' => 'Ghana'],
        ['value' => 'GR', 'en' => 'Greece', 'fi' => 'Kreikka'],
        ['value' => 'GD', 'en' => 'Grenada', 'fi' => 'Grenada'],
        ['value' => 'GT', 'en' => 'Guatemala', 'fi' => 'Guatemala'],
        ['value' => 'GN', 'en' => 'Guinea', 'fi' => 'Guinea'],
        ['value' => 'GW', 'en' => 'Guinea-Bissau', 'fi' => 'Guinea-Bissau'],
        ['value' => 'GY', 'en' => 'Guyana', 'fi' => 'Guyana'],
        ['value' => 'HT', 'en' => 'Haiti', 'fi' => 'Haiti'],
        ['value' => 'HN', 'en' => 'Honduras', 'fi' => 'Honduras'],
        ['value' => 'HU', 'en' => 'Hungary', 'fi' => 'Unkari'],
        ['value' => 'IS', 'en' => 'Iceland', 'fi' => 'Islanti'],
        ['value' => 'IN', 'en' => 'India', 'fi' => 'Intia'],
        ['value' => 'ID', 'en' => 'Indonesia', 'fi' => 'Indonesia'],
        ['value' => 'IR', 'en' => 'Iran', 'fi' => 'Iran'],
        ['value' => 'IQ', 'en' => 'Iraq', 'fi' => 'Irak'],
        ['value' => 'IE', 'en' => 'Ireland', 'fi' => 'Irlanti'],
        ['value' => 'IL', 'en' => 'Israel', 'fi' => 'Israel'],
        ['value' => 'IT', 'en' => 'Italy', 'fi' => 'Italia'],
        ['value' => 'JM', 'en' => 'Jamaica', 'fi' => 'Jamaika'],
        ['value' => 'JP', 'en' => 'Japan', 'fi' => 'Japani'],
        ['value' => 'JO', 'en' => 'Jordan', 'fi' => 'Jordania'],
        ['value' => 'KZ', 'en' => 'Kazakhstan', 'fi' => 'Kazakstan'],
        ['value' => 'KE', 'en' => 'Kenya', 'fi' => 'Kenia'],
        ['value' => 'KI', 'en' => 'Kiribati', 'fi' => 'Kiribati'],
        ['value' => 'XK', 'en' => 'Kosovo', 'fi' => 'Kosovo'],
        ['value' => 'KW', 'en' => 'Kuwait', 'fi' => 'Kuwait'],
        ['value' => 'KG', 'en' => 'Kyrgyzstan', 'fi' => 'Kirgisia'],
        ['value' => 'LA', 'en' => 'Laos', 'fi' => 'Laos'],
        ['value' => 'LV', 'en' => 'Latvia', 'fi' => 'Latvia'],
        ['value' => 'LB', 'en' => 'Lebanon', 'fi' => 'Libanon'],
        ['value' => 'LS', 'en' => 'Lesotho', 'fi' => 'Lesotho'],
        ['value' => 'LR', 'en' => 'Liberia', 'fi' => 'Liberia'],
        ['value' => 'LY', 'en' => 'Libya', 'fi' => 'Libya'],
        ['value' => 'LI', 'en' => 'Liechtenstein', 'fi' => 'Liechtenstein'],
        ['value' => 'LT', 'en' => 'Lithuania', 'fi' => 'Liettua'],
        ['value' => 'LU', 'en' => 'Luxembourg', 'fi' => 'Luxemburg'],
        ['value' => 'MG', 'en' => 'Madagascar', 'fi' => 'Madagaskar'],
        ['value' => 'MW', 'en' => 'Malawi', 'fi' => 'Malawi'],
        ['value' => 'MY', 'en' => 'Malaysia', 'fi' => 'Malesia'],
        ['value' => 'MV', 'en' => 'Maldives', 'fi' => 'Malediivit'],
        ['value' => 'ML', 'en' => 'Mali', 'fi' => 'Mali'],
        ['value' => 'MT', 'en' => 'Malta', 'fi' => 'Malta'],
        ['value' => 'MH', 'en' => 'Marshall Islands', 'fi' => 'Marshallinsaaret'],
        ['value' => 'MR', 'en' => 'Mauritania', 'fi' => 'Mauritania'],
        ['value' => 'MU', 'en' => 'Mauritius', 'fi' => 'Mauritius'],
        ['value' => 'MX', 'en' => 'Mexico', 'fi' => 'Meksiko'],
        ['value' => 'FM', 'en' => 'Micronesia', 'fi' => 'Mikronesia'],
        ['value' => 'MD', 'en' => 'Moldova', 'fi' => 'Moldova'],
        ['value' => 'MC', 'en' => 'Monaco', 'fi' => 'Monaco'],
        ['value' => 'MN', 'en' => 'Mongolia', 'fi' => 'Mongolia'],
        ['value' => 'ME', 'en' => 'Montenegro', 'fi' => 'Montenegro'],
        ['value' => 'MA', 'en' => 'Morocco', 'fi' => 'Marokko'],
        ['value' => 'MZ', 'en' => 'Mozambique', 'fi' => 'Mosambik'],
        ['value' => 'MM', 'en' => 'Myanmar', 'fi' => 'Myanmar'],
        ['value' => 'NA', 'en' => 'Namibia', 'fi' => 'Namibia'],
        ['value' => 'NR', 'en' => 'Nauru', 'fi' => 'Nauru'],
        ['value' => 'NP', 'en' => 'Nepal', 'fi' => 'Nepal'],
        ['value' => 'NL', 'en' => 'Netherlands', 'fi' => 'Alankomaat'],
        ['value' => 'NZ', 'en' => 'New Zealand', 'fi' => 'Uusi-Seelanti'],
        ['value' => 'NI', 'en' => 'Nicaragua', 'fi' => 'Nicaragua'],
        ['value' => 'NE', 'en' => 'Niger', 'fi' => 'Niger'],
        ['value' => 'NG', 'en' => 'Nigeria', 'fi' => 'Nigeria'],
        ['value' => 'KP', 'en' => 'North Korea', 'fi' => 'Pohjois-Korea'],
        ['value' => 'MK', 'en' => 'North Macedonia', 'fi' => 'Pohjois-Makedonia'],
        ['value' => 'NO', 'en' => 'Norway', 'fi' => 'Norja'],
        ['value' => 'OM', 'en' => 'Oman', 'fi' => 'Oman'],
        ['value' => 'PK', 'en' => 'Pakistan', 'fi' => 'Pakistan'],
        ['value' => 'PW', 'en' => 'Palau', 'fi' => 'Palau'],
        ['value' => 'PS', 'en' => 'Palestine', 'fi' => 'Palestiina'],
        ['value' => 'PA', 'en' => 'Panama', 'fi' => 'Panama'],
        ['value' => 'PG', 'en' => 'Papua New Guinea', 'fi' => 'Papua-Uusi-Guinea'],
        ['value' => 'PY', 'en' => 'Paraguay', 'fi' => 'Paraguay'],
        ['value' => 'PE', 'en' => 'Peru', 'fi' => 'Peru'],
        ['value' => 'PH', 'en' => 'Philippines', 'fi' => 'Filippiinit'],
        ['value' => 'PL', 'en' => 'Poland', 'fi' => 'Puola'],
        ['value' => 'PT', 'en' => 'Portugal', 'fi' => 'Portugali'],
        ['value' => 'QA', 'en' => 'Qatar', 'fi' => 'Qatar'],
        ['value' => 'RO', 'en' => 'Romania', 'fi' => 'Romania'],
        ['value' => 'RU', 'en' => 'Russia', 'fi' => 'Venäjä'],
        ['value' => 'RW', 'en' => 'Rwanda', 'fi' => 'Ruanda'],
        ['value' => 'KN', 'en' => 'Saint Kitts and Nevis', 'fi' => 'Saint Kitts ja Nevis'],
        ['value' => 'LC', 'en' => 'Saint Lucia', 'fi' => 'Saint Lucia'],
        ['value' => 'VC', 'en' => 'Saint Vincent and the Grenadines', 'fi' => 'Saint Vincent ja Grenadiinit'],
        ['value' => 'WS', 'en' => 'Samoa', 'fi' => 'Samoa'],
        ['value' => 'SM', 'en' => 'San Marino', 'fi' => 'San Marino'],
        ['value' => 'ST', 'en' => 'São Tomé and Príncipe', 'fi' => 'São Tomé ja Príncipe'],
        ['value' => 'SA', 'en' => 'Saudi Arabia', 'fi' => 'Saudi-Arabia'],
        ['value' => 'SN', 'en' => 'Senegal', 'fi' => 'Senegal'],
        ['value' => 'RS', 'en' => 'Serbia', 'fi' => 'Serbia'],
        ['value' => 'SC', 'en' => 'Seychelles', 'fi' => 'Seychellit'],
        ['value' => 'SL', 'en' => 'Sierra Leone', 'fi' => 'Sierra Leone'],
        ['value' => 'SG', 'en' => 'Singapore', 'fi' => 'Singapore'],
        ['value' => 'SK', 'en' => 'Slovakia', 'fi' => 'Slovakia'],
        ['value' => 'SI', 'en' => 'Slovenia', 'fi' => 'Slovenia'],
        ['value' => 'SB', 'en' => 'Solomon Islands', 'fi' => 'Salomonsaaret'],
        ['value' => 'SO', 'en' => 'Somalia', 'fi' => 'Somalia'],
        ['value' => 'ZA', 'en' => 'South Africa', 'fi' => 'Etelä-Afrikka'],
        ['value' => 'KR', 'en' => 'South Korea', 'fi' => 'Etelä-Korea'],
        ['value' => 'SS', 'en' => 'South Sudan', 'fi' => 'Etelä-Sudan'],
        ['value' => 'ES', 'en' => 'Spain', 'fi' => 'Espanja'],
        ['value' => 'LK', 'en' => 'Sri Lanka', 'fi' => 'Sri Lanka'],
        ['value' => 'SD', 'en' => 'Sudan', 'fi' => 'Sudan'],
        ['value' => 'SR', 'en' => 'Suriname', 'fi' => 'Suriname'],
        ['value' => 'SE', 'en' => 'Sweden', 'fi' => 'Ruotsi'],
        ['value' => 'CH', 'en' => 'Switzerland', 'fi' => 'Sveitsi'],
        ['value' => 'SY', 'en' => 'Syria', 'fi' => 'Syyria'],
        ['value' => 'TW', 'en' => 'Taiwan', 'fi' => 'Taiwan'],
        ['value' => 'TJ', 'en' => 'Tajikistan', 'fi' => 'Tadžikistan'],
        ['value' => 'TZ', 'en' => 'Tanzania', 'fi' => 'Tansania'],
        ['value' => 'TH', 'en' => 'Thailand', 'fi' => 'Thaimaa'],
        ['value' => 'TL', 'en' => 'Timor-Leste', 'fi' => 'Itä-Timor'],
        ['value' => 'TG', 'en' => 'Togo', 'fi' => 'Togo'],
        ['value' => 'TO', 'en' => 'Tonga', 'fi' => 'Tonga'],
        ['value' => 'TT', 'en' => 'Trinidad and Tobago', 'fi' => 'Trinidad ja Tobago'],
        ['value' => 'TN', 'en' => 'Tunisia', 'fi' => 'Tunisia'],
        ['value' => 'TR', 'en' => 'Turkey', 'fi' => 'Turkki'],
        ['value' => 'TM', 'en' => 'Turkmenistan', 'fi' => 'Turkmenistan'],
        ['value' => 'TV', 'en' => 'Tuvalu', 'fi' => 'Tuvalu'],
        ['value' => 'UG', 'en' => 'Uganda', 'fi' => 'Uganda'],
        ['value' => 'UA', 'en' => 'Ukraine', 'fi' => 'Ukraina'],
        ['value' => 'AE', 'en' => 'United Arab Emirates', 'fi' => 'Yhdistyneet arabiemiirikunnat'],
        ['value' => 'GB', 'en' => 'United Kingdom', 'fi' => 'Yhdistynyt kuningaskunta'],
        ['value' => 'US', 'en' => 'United States', 'fi' => 'Yhdysvallat'],
        ['value' => 'UY', 'en' => 'Uruguay', 'fi' => 'Uruguay'],
        ['value' => 'UZ', 'en' => 'Uzbekistan', 'fi' => 'Uzbekistan'],
        ['value' => 'VU', 'en' => 'Vanuatu', 'fi' => 'Vanuatu'],
        ['value' => 'VA', 'en' => 'Vatican City', 'fi' => 'Vatikaani'],
        ['value' => 'VE', 'en' => 'Venezuela', 'fi' => 'Venezuela'],
        ['value' => 'VN', 'en' => 'Vietnam', 'fi' => 'Vietnam'],
        ['value' => 'YE', 'en' => 'Yemen', 'fi' => 'Jemen'],
        ['value' => 'ZM', 'en' => 'Zambia', 'fi' => 'Sambia'],
        ['value' => 'ZW', 'en' => 'Zimbabwe', 'fi' => 'Zimbabwe'],
    ];

    /**
     * Return a human-readable country label for the given ISO 3166-1 alpha-2 code.
     * Falls back to the raw code if not found.
     */
    public static function getLabel(string $code, string $locale = 'en'): string
    {
        $code   = strtoupper($code);
        $locale = in_array($locale, ['en', 'fi']) ? $locale : 'en';

        foreach (self::$countries as $country) {
            if ($country['value'] === $code) {
                return $country[$locale];
            }
        }

        return $code;
    }

    public static function all(): array
    {
        return self::$countries;
    }
}
