steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=${_IMAGE}
      - --cache=true
      - --cache-ttl=168h
      - --compressed-caching=false
      - --snapshot-mode=redo
      - --use-new-run=true
      - --context=dir:///workspace
      - --dockerfile=Dockerfile

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - jussilog-backend-production
      - --image
      - ${_IMAGE}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - APP_ENV=production,APP_DEBUG=false,DB_CONNECTION=sqlite,APP_KEY=${_APP_KEY}
      - --min-instances=0
      - --max-instances=1
      - --memory=512Mi
      - --cpu=1
      - --concurrency=80
      - --timeout=60

images:
  - ${_IMAGE}

substitutions:
  _REGION: europe-north1
  _IMAGE: europe-north1-docker.pkg.dev/client-jussimatic/jussilog-backend/jussilog-backend:latest
  _APP_KEY: ''

timeout: 360s

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_2
  diskSizeGb: 10
