[www]
user = laravel
group = laravel

listen = 127.0.0.1:9000

pm = static
pm.max_children = 8

; Ensure environment variables are passed to PHP
clear_env = no

; Catch worker output
catch_workers_output = yes

; Fix PATH
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
